name: PR labeler
on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
    branches:
      - main
      - phase-* # This will run on any branch that starts with "phase-"
jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - name: label-by-size
        uses: pascalgn/size-label-action@v0.4.3
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          IGNORED: "package-lock.json"